# local vagrant settings for carmacar

# specification of the environment
environment: vagrant

# Give the box a name
box-name: <%= boxname %>

# Webserver
nginx:
  enabled: <%= installNginx %>

  # User and group for Nginx
  user: ubuntu
  group: ubuntu

  # Install support for xdebug
  xdebug: true

  # Install composer (default: true)
  composer: true

  # configuration of vhosts
  vhosts:
    - shortname: <%= appname %>

      # Host folder where sources are located
      src_folder: "../"

      # Document root
      attributes:
        document_root: "application/public"

      # enable self signed SSL
      ssl_enabled: <%= enableSSL %>

      # Rewrite rules (required for certain frameworks)
      environment:
        rewrite_to_index_php: "true"
        rewrite_to_index_html: "false"

      # Domains the vhost should listen to
      domains:
        - <%= defaultValues.host %>

# Mysql
mysql:
  enabled: <%= installMysql %>

  # Root User password
  root_password: <%= defaultValues.mysqlRootPwd %>

  # Admin User password
  admin_password: <%= defaultValues.mysqlAdminPwd %>

  # Name of the database
  databases:
    - <%= databaseName %>

# Build tools
build-tools:
  enabled: true

########################################################################################################################
##################### Do not change anything below unless you know what you are doing! #################################
########################################################################################################################

# configuration of the vm
vm:
  private_ip: 10.0.0.42
  memory: 2048
  cpus: 1

# Location where the current stable version of chef cookbooks can be found
cookbooks_path: /media/Produkte_Web-Projekte/_Allgemein/_Produkte_DevOps/chef_cookbooks/master-1.6.0